# conf port
server:
  port: 3000

# conf server or no server
spring:
  profiles:
    active: development # this is profile for logback

  main:
    web-application-type: servlet

  # conf database address and auth
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: postgres
    password: postgres

  # forgot what that is
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # conf spring secruity auth
  security:
    user:
      name: spring
      password: spring