# Server Configuration
server:
  port: 3001

# Spring Framework Configuration
spring:
  # Application Profile
  profiles:
    active: development # Profile for logback configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  # Web Application Configuration
  main:
    web-application-type: servlet

  # JSON Serialization Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    #       ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Spring Security Configuration
  security:
    user:
      name: spring
      password: spring

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Custom Application Properties
appointment:
  min:
    hours:
      in:
        advance: 8
  max:
    months:
      in:
        advance: 6

# File Upload Configuration
app:
  file:
    upload:
      root-directory: ${user.home}/clinic-files
      avatars:
        directory: avatars
        max-size: 5MB
        allowed-extensions: jpg,jpeg,png,webp
      treatments:
        directory: treatments
        max-size: 10MB
        allowed-extensions: pdf,jpg,jpeg,png,doc,docx,txt
      default-avatar: src/main/resources/static/default-avatar.png